name: dropdown_below
description: flutter custom dropdown box. Develeoper can customize many options for there taste. It can be huge advantage for dropdown ux
version: 0.0.2
homepage: https://github.com/whatamelon/flutter_dropdown_below

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
