name: dropdown_below
description: flutter custom dropdown box.
version: 0.0.1
author: whatamelon<a01042040716@gmail.com>
homepage: https://github.com/whatamelon/dropdown_below.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
